/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/myicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'myicons';

  static const IconData menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData share__1_ = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData Home = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData settings__1_ = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe808, fontFamily: _kFontFam);
}
